# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZgTbLVDbbPs0kwzpIRazp974cQXmOlVM
"""



import os
import random
import shutil

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from torchvision import transforms, models
from torchvision.models import (
    ResNet18_Weights,
    MobileNet_V3_Small_Weights,
    EfficientNet_B0_Weights
)

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    ConfusionMatrixDisplay
)

import os
import zipfile
import shutil
import torch

# ==============================
# UNZIP DATASET
# ==============================

ZIP_FILE = "/content/dataset.zip"
EXTRACT_DIR = "/content/product_data"

# Remove old extraction if it exists
if os.path.exists(EXTRACT_DIR):
    shutil.rmtree(EXTRACT_DIR)

os.makedirs(EXTRACT_DIR, exist_ok=True)

# Verify ZIP before extraction
if not zipfile.is_zipfile(ZIP_FILE):
    raise ValueError("dataset.zip is not a valid ZIP file.")

with zipfile.ZipFile(ZIP_FILE, "r") as zip_ref:
    zip_ref.extractall(EXTRACT_DIR)

print("Dataset extracted successfully!")

# ==============================
# PATHS
# ==============================

# ZIP structure:
# dataset/
# ├── train/
# ├── test/
# └── train.csv

DATA_DIR = os.path.join(EXTRACT_DIR, "dataset")

TRAIN_DIR = os.path.join(DATA_DIR, "train")
TEST_DIR = os.path.join(DATA_DIR, "test")
CSV_FILE = os.path.join(DATA_DIR, "train.csv")

# ==============================
# OUTPUT DIRECTORIES
# ==============================

MODEL_DIR = "/content/Model"
RESULTS_DIR = "/content/results"

os.makedirs(MODEL_DIR, exist_ok=True)
os.makedirs(RESULTS_DIR, exist_ok=True)

# ==============================
# SETTINGS
# ==============================

IMAGE_SIZE = 224
BATCH_SIZE = 16
EPOCHS = 10
LEARNING_RATE = 0.001
SEED = 42

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

# ==============================
# VERIFY DATASET
# ==============================

print("==============================================")
print("AUTOMATED PRODUCT DEFECT DETECTION")
print("==============================================")
print("Device:", device)

print("\nDataset paths:")
print("DATA_DIR :", DATA_DIR)
print("TRAIN    :", TRAIN_DIR)
print("TEST     :", TEST_DIR)
print("CSV      :", CSV_FILE)

print("\nDataset contents:")
print(os.listdir(DATA_DIR))

print("\nTrain exists:", os.path.exists(TRAIN_DIR))
print("Test exists :", os.path.exists(TEST_DIR))
print("CSV exists  :", os.path.exists(CSV_FILE))

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

# ============================================================
# 3. LOAD CSV
# ============================================================

df = pd.read_csv(CSV_FILE)

print("\nDataset columns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
print(df.head())

print("\nTotal images:", len(df))

# ============================================================
# 4. PREPARE LABELS
# ============================================================

# anomaly = 0 -> Normal
# anomaly = 1 -> Defective

df["label"] = df["anomaly"].astype(int)

df["image_path"] = df["filename"].apply(
    lambda x: os.path.join(TRAIN_DIR, x)
)

print("\nClass distribution:")
print(df["label"].value_counts())

# ============================================================
# 5. CHECK MISSING IMAGES
# ============================================================

missing_images = df[
    ~df["image_path"].apply(os.path.exists)
]

if len(missing_images) > 0:

    print("\nWARNING: Missing images found:")
    print(missing_images.head())

else:

    print("\nAll training images found.")

# ============================================================
# 6. TRAIN / VALIDATION SPLIT
# ============================================================

train_df, val_df = train_test_split(
    df,
    test_size=0.20,
    random_state=SEED,
    stratify=df["label"]
)

train_df = train_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)

print("\nTraining images:", len(train_df))
print("Validation images:", len(val_df))

print("\nTraining distribution:")
print(train_df["label"].value_counts())

print("\nValidation distribution:")
print(val_df["label"].value_counts())

# ============================================================
# 7. IMAGE TRANSFORMATION
# ============================================================


transform = transforms.Compose([

    transforms.Resize(
        (IMAGE_SIZE, IMAGE_SIZE)
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# ============================================================
# 8. CUSTOM DATASET
# ============================================================

class ScrewDataset(Dataset):

    def __init__(self, dataframe, transform=None):

        self.dataframe = dataframe
        self.transform = transform

    def __len__(self):

        return len(self.dataframe)

    def __getitem__(self, index):

        row = self.dataframe.iloc[index]

        image_path = row["image_path"]
        label = int(row["label"])
        filename = row["filename"]

        image = Image.open(
            image_path
        ).convert("RGB")

        if self.transform:
            image = self.transform(image)

        return image, label, filename

# ============================================================
# 9. DATASETS
# ============================================================

train_dataset = ScrewDataset(
    train_df,
    transform
)

val_dataset = ScrewDataset(
    val_df,
    transform
)

# ============================================================
# 10. DATALOADERS
# ============================================================

num_workers = 2 if torch.cuda.is_available() else 0

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=num_workers
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=num_workers
)

print("\nDataLoaders created.")

# ============================================================
# 11. MODEL CREATION FUNCTIONS
# ============================================================

def create_resnet18():

    weights = ResNet18_Weights.DEFAULT

    model = models.resnet18(
        weights=weights
    )

    # Freeze pretrained layers
    for parameter in model.parameters():
        parameter.requires_grad = False

    # Replace final layer
    num_features = model.fc.in_features

    model.fc = nn.Linear(
        num_features,
        2
    )

    return model


def create_mobilenet():

    weights = MobileNet_V3_Small_Weights.DEFAULT

    model = models.mobilenet_v3_small(
        weights=weights
    )

    # Freeze pretrained layers
    for parameter in model.parameters():
        parameter.requires_grad = False

    # Replace final classifier
    num_features = model.classifier[-1].in_features

    model.classifier[-1] = nn.Linear(
        num_features,
        2
    )

    return model


def create_efficientnet():

    weights = EfficientNet_B0_Weights.DEFAULT

    model = models.efficientnet_b0(
        weights=weights
    )

    # Freeze pretrained layers
    for parameter in model.parameters():
        parameter.requires_grad = False

    # Replace final classifier
    num_features = model.classifier[-1].in_features

    model.classifier[-1] = nn.Linear(
        num_features,
        2
    )

    return model

# ============================================================
# 12. MODEL DICTIONARY
# ============================================================

model_creators = {

    "ResNet18": create_resnet18,

    "MobileNetV3-Small": create_mobilenet,

    "EfficientNet-B0": create_efficientnet
}

# ============================================================
# 13. TRAINING FUNCTION
# ============================================================

def train_model(model_name, model):

    print("\n")
    print("================================================")
    print(f"TRAINING: {model_name}")
    print("================================================")

    model = model.to(device)

    criterion = nn.CrossEntropyLoss()

    # Only train parameters that are not frozen
    trainable_parameters = filter(
        lambda p: p.requires_grad,
        model.parameters()
    )

    optimizer = torch.optim.Adam(
        trainable_parameters,
        lr=LEARNING_RATE
    )

    train_losses = []
    val_losses = []

    train_accuracies = []
    val_accuracies = []

    best_val_f1 = 0.0

    model_results_dir = os.path.join(
        RESULTS_DIR,
        model_name.replace("-", "_")
    )

    os.makedirs(
        model_results_dir,
        exist_ok=True
    )

    model_path = os.path.join(
        MODEL_DIR,
        f"{model_name.replace('-', '_')}.pth"
    )

    # ========================================================
    # TRAINING LOOP
    # ========================================================

    for epoch in range(EPOCHS):

      # ========================================================
      # TRAIN
      # ========================================================


        model.train()

        running_loss = 0.0

        correct = 0
        total = 0

        for images, labels, filenames in train_loader:

            images = images.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            outputs = model(images)

            loss = criterion(
                outputs,
                labels
            )

            loss.backward()

            optimizer.step()

            running_loss += (
                loss.item() *
                images.size(0)
            )

            _, predictions = torch.max(
                outputs,
                1
            )

            total += labels.size(0)

            correct += (
                predictions == labels
            ).sum().item()

        train_loss = running_loss / total

        train_accuracy = correct / total


        # ----------------------------------------------------
        # VALIDATION
        # ----------------------------------------------------

        model.eval()

        val_running_loss = 0.0

        val_correct = 0
        val_total = 0

        val_labels_epoch = []
        val_predictions_epoch = []

        with torch.no_grad():

            for images, labels, filenames in val_loader:

                images = images.to(device)
                labels = labels.to(device)

                outputs = model(images)

                loss = criterion(
                    outputs,
                    labels
                )

                val_running_loss += (
                    loss.item() *
                    images.size(0)
                )

                _, predictions = torch.max(
                    outputs,
                    1
                )

                val_total += labels.size(0)

                val_correct += (
                    predictions == labels
                ).sum().item()

                val_labels_epoch.extend(
                    labels.cpu().numpy()
                )

                val_predictions_epoch.extend(
                    predictions.cpu().numpy()
                )

        val_loss = (
            val_running_loss /
            val_total
        )

        val_accuracy = (
            val_correct /
            val_total
        )

        val_f1 = f1_score(
            val_labels_epoch,
            val_predictions_epoch,
            zero_division=0
        )


        # ----------------------------------------------------
        # STORE RESULTS
        # ----------------------------------------------------

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        train_accuracies.append(
            train_accuracy
        )

        val_accuracies.append(
            val_accuracy
        )


        print(
            f"Epoch [{epoch + 1}/{EPOCHS}] "
            f"| Train Loss: {train_loss:.4f} "
            f"| Train Acc: {train_accuracy:.4f} "
            f"| Val Loss: {val_loss:.4f} "
            f"| Val Acc: {val_accuracy:.4f} "
            f"| Val F1: {val_f1:.4f}"
        )


        # ----------------------------------------------------
        # SAVE BEST MODEL
        # ----------------------------------------------------

        if val_f1 > best_val_f1:

            best_val_f1 = val_f1

            torch.save(
                model.state_dict(),
                model_path
            )

            print(
                "   -> Best model saved."
            )


    # ========================================================
    # LOAD BEST MODEL
    # ========================================================

    model.load_state_dict(
        torch.load(
            model_path,
            map_location=device
        )
    )

    model.eval()


    # ========================================================
    # FINAL VALIDATION PREDICTIONS
    # ========================================================

    all_labels = []
    all_predictions = []
    all_filenames = []

    with torch.no_grad():

        for images, labels, filenames in val_loader:

            images = images.to(device)

            outputs = model(images)

            _, predictions = torch.max(
                outputs,
                1
            )

            all_labels.extend(
                labels.numpy()
            )

            all_predictions.extend(
                predictions.cpu().numpy()
            )

            all_filenames.extend(
                filenames
            )


    # ========================================================
    # METRICS
    # ========================================================

    accuracy = accuracy_score(
        all_labels,
        all_predictions
    )

    precision = precision_score(
        all_labels,
        all_predictions,
        zero_division=0
    )

    recall = recall_score(
        all_labels,
        all_predictions,
        zero_division=0
    )

    f1 = f1_score(
        all_labels,
        all_predictions,
        zero_division=0
    )

    cm = confusion_matrix(
        all_labels,
        all_predictions
    )


    print("\nFinal validation results:")
    print(f"Accuracy  : {accuracy:.4f}")
    print(f"Precision : {precision:.4f}")
    print(f"Recall    : {recall:.4f}")
    print(f"F1 Score  : {f1:.4f}")


    # ========================================================
    # SAVE METRICS
    # ========================================================

    metrics_path = os.path.join(
        model_results_dir,
        "metrics.txt"
    )

    with open(
        metrics_path,
        "w"
    ) as f:

        f.write(
            f"{model_name} Validation Results\n"
        )

        f.write(
            "================================\n\n"
        )

        f.write(
            f"Accuracy  : {accuracy:.4f}\n"
        )

        f.write(
            f"Precision : {precision:.4f}\n"
        )

        f.write(
            f"Recall    : {recall:.4f}\n"
        )

        f.write(
            f"F1 Score  : {f1:.4f}\n\n"
        )

        f.write(
            "Confusion Matrix:\n"
        )

        f.write(
            str(cm)
        )


    # ========================================================
    # LOSS CURVE
    # ========================================================

    plt.figure(figsize=(8, 5))

    plt.plot(
        range(1, EPOCHS + 1),
        train_losses,
        label="Training Loss"
    )

    plt.plot(
        range(1, EPOCHS + 1),
        val_losses,
        label="Validation Loss"
    )

    plt.xlabel("Epoch")
    plt.ylabel("Loss")

    plt.title(
        f"{model_name} - Loss Curve"
    )

    plt.legend()
    plt.grid()

    plt.savefig(
        os.path.join(
            model_results_dir,
            "loss_curve.png"
        ),
        dpi=300,
        bbox_inches="tight"
    )

    plt.close()


    # ========================================================
    # ACCURACY CURVE
    # ========================================================

    plt.figure(figsize=(8, 5))

    plt.plot(
        range(1, EPOCHS + 1),
        train_accuracies,
        label="Training Accuracy"
    )

    plt.plot(
        range(1, EPOCHS + 1),
        val_accuracies,
        label="Validation Accuracy"
    )

    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")

    plt.title(
        f"{model_name} - Accuracy Curve"
    )

    plt.legend()
    plt.grid()

    plt.savefig(
        os.path.join(
            model_results_dir,
            "accuracy_curve.png"
        ),
        dpi=300,
        bbox_inches="tight"
    )

    plt.close()


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    fig, ax = plt.subplots(
        figsize=(6, 6)
    )

    disp = ConfusionMatrixDisplay(
        confusion_matrix=cm,
        display_labels=[
            "Normal",
            "Defective"
        ]
    )

    disp.plot(
        ax=ax,
        values_format="d"
    )

    plt.title(
        f"{model_name} - Confusion Matrix"
    )

    plt.savefig(
        os.path.join(
            model_results_dir,
            "confusion_matrix.png"
        ),
        dpi=300,
        bbox_inches="tight"
    )

    plt.close()


    # ========================================================
    # MISCLASSIFIED IMAGES
    # ========================================================

    misclassified_dir = os.path.join(
        model_results_dir,
        "misclassified"
    )

    os.makedirs(
        misclassified_dir,
        exist_ok=True
    )

    misclassified_indices = []

    for i in range(
        len(all_labels)
    ):

        if (
            all_labels[i]
            !=
            all_predictions[i]
        ):

            misclassified_indices.append(i)


    # Save maximum 3
    for count, index in enumerate(
        misclassified_indices[:3]
    ):

        filename = all_filenames[index]

        source_path = os.path.join(
            TRAIN_DIR,
            filename
        )

        destination_path = os.path.join(
            misclassified_dir,
            f"error_{count + 1}_{filename}"
        )

        shutil.copy(
            source_path,
            destination_path
        )


    # ========================================================
    # RETURN RESULTS
    # ========================================================

    return {
        "model": model_name,
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "model_path": model_path,
        "validation_labels": all_labels,
        "validation_predictions": all_predictions,
        "validation_filenames": all_filenames,
        "model_object": model
    }

# ============================================================
# 14. TRAIN ALL THREE MODELS
# ============================================================

all_results = []


for model_name, model_creator in model_creators.items():

    print("\n\n")
    print("################################################")
    print(f"STARTING {model_name}")
    print("################################################")

    model = model_creator()

    result = train_model(
        model_name,
        model
    )

    all_results.append(
        result
    )

# ============================================================
# 15. MODEL COMPARISON
# ============================================================

comparison_df = pd.DataFrame([

    {
        "Model": result["model"],
        "Accuracy": result["accuracy"],
        "Precision": result["precision"],
        "Recall": result["recall"],
        "F1": result["f1"]
    }

    for result in all_results
])


comparison_df = comparison_df.sort_values(
    by="F1",
    ascending=False
)

comparison_df = comparison_df.reset_index(
    drop=True
)


print("\n")
print("================================================")
print("MODEL COMPARISON")
print("================================================")

print(
    comparison_df.to_string(
        index=False
    )
)


comparison_df.to_csv(
    os.path.join(
        RESULTS_DIR,
        "model_comparison.csv"
    ),
    index=False
)

# ============================================================
# 16. SELECT BEST MODEL
# ============================================================

best_model_name = comparison_df.iloc[0]["Model"]

best_result = next(
    result
    for result in all_results
    if result["model"] == best_model_name
)

best_model = best_result["model_object"]

best_model_path = best_result["model_path"]


print("\nBest model:")
print(best_model_name)

print(
    f"Best F1 Score: "
    f"{best_result['f1']:.4f}"
)

# ============================================================
# 17. FINAL TEST PREDICTIONS
# ============================================================

print("\n")
print("================================================")
print("PREDICTING UNSEEN TEST DATA")
print("================================================")


test_filenames = [

    filename

    for filename in os.listdir(TEST_DIR)

    if filename.lower().endswith(
        (".png", ".jpg", ".jpeg")
    )
]

test_filenames.sort()


test_predictions = []


best_model.eval()


with torch.no_grad():

    for filename in test_filenames:

        image_path = os.path.join(
            TEST_DIR,
            filename
        )

        image = Image.open(
            image_path
        ).convert("RGB")

        image = transform(image)

        image = image.unsqueeze(0)

        image = image.to(device)

        output = best_model(image)

        _, prediction = torch.max(
            output,
            1
        )

        prediction = prediction.item()

        class_name = (

            "Defective"

            if prediction == 1

            else "Normal"
        )

        test_predictions.append({

            "filename": filename,

            "prediction": prediction,

            "class": class_name

        })

# ============================================================
# 18. SAVE TEST PREDICTIONS
# ============================================================

test_predictions_df = pd.DataFrame(
    test_predictions
)

test_predictions_path = os.path.join(
    RESULTS_DIR,
    "test_predictions.csv"
)

test_predictions_df.to_csv(
    test_predictions_path,
    index=False
)


print(
    "\nTest predictions saved to:"
)

print(
    test_predictions_path
)

print("\nFirst 10 predictions:")

print(
    test_predictions_df.head(10)
)

# ============================================================
# 19. SAVE FINAL SUMMARY
# ============================================================

summary_path = os.path.join(
    RESULTS_DIR,
    "final_summary.txt"
)

with open(
    summary_path,
    "w"
) as f:

    f.write(
        "Automated Product Defect Detection\n"
    )

    f.write(
        "====================================\n\n"
    )

    f.write(
        "Models compared:\n"
    )

    f.write(
        "1. ResNet18\n"
    )

    f.write(
        "2. MobileNetV3-Small\n"
    )

    f.write(
        "3. EfficientNet-B0\n\n"
    )

    f.write(
        comparison_df.to_string(
            index=False
        )
    )

    f.write(
        "\n\nBest Model: "
        + best_model_name
    )

    f.write(
        f"\nBest F1 Score: "
        f"{best_result['f1']:.4f}"
    )

# ============================================================
# 20. FINAL OUTPUT
# ============================================================

print("\n")
print("================================================")
print("PROJECT COMPLETED SUCCESSFULLY")
print("================================================")

print("\nModels saved in:")
print("Model/")

print("\nResults saved in:")
print("results/")

print("\nBest model:")
print(best_model_name)

print("\nValidation performance:")
print(
    comparison_df.to_string(
        index=False
    )
)

print("\nTest predictions:")
print(test_predictions_path)

print("\nDone!")

!git clone https://github.com/mshreya006/automated_product_defect_detection.git

!ls -la /content/automated_product_defect_detection